version: '2'
services:
  competitiveprogrammingarena-app:
    image: competitiveprogrammingarena
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://competitiveprogrammingarena-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=competitiveProgrammingArena
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  competitiveprogrammingarena-mongodb:
    extends:
      file: mongodb.yml
      service: competitiveprogrammingarena-mongodb
