version: '2'
services:
  competitiveprogrammingarena-mongodb:
    image: mongo:4.0.16
    ports:
      - '27017:27017'
    command: mongos --configdb competitiveprogrammingarena-mongodb-config
  competitiveprogrammingarena-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  competitiveprogrammingarena-mongodb-config:
    image: mongo:4.0.16
    container_name: competitiveprogrammingarena-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
